# site information
site_name: 智能传感系统与机器人实验室 # 左上角标题
site_url: https://juhaocui.github.io/
site_author: JuhaoCui
site_description: Welcome to our lab!

# navigation
nav:
  - Home:
    - test: test.md
  - Members:
    - Director: director.md
    - Ph.D Students: phd.md
    - Master Students: master.md
  - Publications: pub.md
  - Research: research.md
  - Projects: proj.md
  - News & Blog: news.md
  - Join us: us.md
  - other: 
    - Equipment: equip.md
    - Gallery: picture.md
      
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github

# copyright
copyright: JuhaoCui
