# site information
site_name: junhaocui
site_url: https://juhaocui.github.io/
site_description: hello

# navigation
-nv:
  -test: test.md
  -test2: test2.md
  # -Automated Assembly Line: Automated Line.md
  
# theme
theme:
  name: material
  #logo: logo.png
  font:
   text: Playfair Display

# copyright
copyright: junhaocui
